### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by K-RKY** [K-RKY/protospace-38108#1]
https://protospace-38108.herokuapp.com/

**Comment by shodai-ito** [comment]
@K-RKY さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされること**
ログアウト状態で編集ページに遷移しようとすると、ログインページでなくトップページへ遷移してしまいます。

【チェック方法】
最初にログアウト状態を作る。投稿ページ・編集ページのURLを打ち込み、ログインページにリダイレクトされれば正常な挙動。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by K-RKY** [comment]
ご確認頂きありがとうございます。
上記内容修正致しました。

**Comment by motomuun** [comment]
@K-RKY さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by K-RKY** [comment]
ご確認頂きありがとうございます。
